DROP TABLE EMPRESA;
DROP TABLE EMPRESA_DIFUSORA;
DROP TABLE ARTISTA;
DROP TABLE VENTAS;
DROP TABLE REGALIAS;
DROP TABLE USUARIO;
DROP TABLE LOG;
DROP TABLE INFORMES;

CREATE TABLE EMPRESA 
(
    ID_EMPRESA INTEGER,
    NOMBRE_EMPRESA VARCHAR2(20),
    NIT_EMPRESA VARCHAR2(15),
    TIPOR_REGALIA_D VARCHAR2(15),
    VALOR_REGALIA NUMBER(4,2)
)
TABLESPACE SSMUSIC;

CREATE TABLE EMPRESA_DIFUSORA 
(
    ID_EMPRESA_D INTEGER,
    ID_EMAYOR INTEGER,
    NIT_EMPRESA_D VARCHAR2(30),
    NOM_EMPRESA_D VARCHAR2(50),
    NOM_ENCARGADO_D VARCHAR2(50),
    DOC_ENCARGADO_D VARCHAR2(40),
    TEL_ENCARGADO_D VARCHAR2(40),
    COR_ENCARGADO_D VARCHAR2(40),
    TIPO_OPERACION_D VARCHAR2(15),
    VALOR_OPERACION_D NUMBER(4,2),
    FECHA_REGISTRO_D VARCHAR2(40)
)
TABLESPACE SSMUSIC;

CREATE TABLE ARTISTA 
(
    ID_ARTISTA INTEGER,
    NOM_ARTISTA VARCHAR2(40),
    NOM_REPRESENTANTE VARCHAR2(40),
    DOC_REPRESENTANTE VARCHAR2(40),
    TEL_REPRESENTANTE VARCHAR2(40),
    COR_REPRESENTANTE VARCHAR2(40),
    ID_EMPRESA_D_ART INTEGER,
    FECHA_REGISTRO_ART DATE
)
TABLESPACE SSMUSIC;

CREATE TABLE VENTAS
(
    ID_VENTAS INTEGER,
    ID_ARTISTA_VE INTEGER,
    CANTIDAD_OPERACIONES INTEGER,
    VALOR_VENTA NUMBER(4,2),
    FECHA_VENTA DATE
)
TABLESPACE SSMUSIC;

CREATE TABLE REGALIAS 
(
    ID_REGALIAS INTEGER,
    ID_VENTAS_RE INTEGER,
    VALOR_TOTAL NUMBER(4,2),
    TIPO_DE_REGALIA VARCHAR2(40)
)
TABLESPACE SSMUSIC;

CREATE TABLE USUARIO
(
    ID_USUARIO INTEGER,
    ID_EMPRESA_U INTEGER,
    TIPO_PERFIL VARCHAR2(6),
    USERNAME VARCHAR2(20),
    PASS VARCHAR2(20),
    NOMBRES VARCHAR2(40),
    APELLIDO1 VARCHAR2(40),
    APELLIDO2 VARCHAR2(40),
    DOCUMENTO VARCHAR2(20),
    CORREO VARCHAR2(40),
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(40),
    FECHA_REGISTRO DATE
)
TABLESPACE SSMUSIC;

CREATE TABLE LOG
(
   ID_LOG INTEGER,
   ID_USUARIO_LOG INTEGER,
   TIPO_DE_GESTION VARCHAR2(40),
   FECHA_LOG DATE
)
TABLESPACE SSMUSIC;

CREATE TABLE INFORMES
(
    ID_INFORME INTEGER,
    ID_USUARIO_INF INTEGER,
    TIPO_DE_INFORME VARCHAR2(40)
)
TABLESPACE SSMUSIC;