--TRIGGER EMPRESA--
CREATE OR REPLACE TRIGGER TG_ID_EMPRESA
BEFORE INSERT ON EMPRESA
FOR EACH ROW
BEGIN	
	DECLARE 
		WEMPRESA INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_EMPRESA.NEXTVAL INTO WEMPRESA FROM DUAL;
			:new.ID_EMPRESA :=WEMPRESA;
		END;
END;
/
--TRIGGER EMPRESA DIFUSORA--
CREATE OR REPLACE TRIGGER TG_ID_EMPRESA_DIFUROSA
BEFORE INSERT ON EMPRESA_DIFUSORA
FOR EACH ROW
BEGIN	
	DECLARE 
		WID_EMPRESA_D INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_EMPRESA_DIFUSORA.NEXTVAL INTO WID_EMPRESA_D FROM DUAL;
			:new.ID_EMPRESA_D:=WID_EMPRESA_D;
		END;
END;
/

--TRIGGER ARTISTA--
CREATE OR REPLACE TRIGGER TG_ID_ARTISTA
BEFORE INSERT ON ARTISTA
FOR EACH ROW
BEGIN	
	DECLARE 
		WID_ARTISTA INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_ARTISTA.NEXTVAL INTO WID_ARTISTA FROM DUAL;
			:new.ID_ARTISTA:=WID_ARTISTA;
		END;
END;
/

--TRIGGER USUARIO--
CREATE OR REPLACE TRIGGER TG_ID_USUARIO
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN	
	DECLARE 
		WID_USUARIO INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_USUARIO.NEXTVAL INTO WID_USUARIO FROM DUAL;
			:new.ID_USUARIO:=WID_USUARIO;
		END;
END;
/

--TRIGGER LOG--
CREATE OR REPLACE TRIGGER TG_ID_LOG
BEFORE INSERT ON LOG
FOR EACH ROW
BEGIN	
	DECLARE 
		WID_LOG INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_LOG.NEXTVAL INTO WID_LOG FROM DUAL;
			:new.ID_LOG:=WID_LOG;
		END;
END;
/
